src/Entity/Person.php
<?php namespace App\Entity;

use App\Util\Stringy;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Persistence\PersonRepository")
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
 * @ORM\Table(name="person",
 *	indexes={
 *		@ORM\Index(name="name_idx", columns={"name"}),
 *		@ORM\Index(name="last_name_idx", columns={"last_name"}),
 *		@ORM\Index(name="orig_name_idx", columns={"orig_name"}),
 *		@ORM\Index(name="real_name_idx", columns={"real_name"}),
 *		@ORM\Index(name="oreal_name_idx", columns={"oreal_name"}),
 *		@ORM\Index(name="country_idx", columns={"country"}),
 *		@ORM\Index(name="is_author_idx", columns={"is_author"}),
 *		@ORM\Index(name="is_translator_idx", columns={"is_translator"})}
 * )
 * @UniqueEntity(fields="slug", message="This slug is already in use.")
 */
class Person extends Entity implements \JsonSerializable {
	/**
	 * @ORM\Column(type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="CUSTOM")
	 * @ORM\CustomIdGenerator(class="App\Doctrine\CustomIdGenerator")
	 */
	private $id;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=50, unique=true)
	 */
	private $slug;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100)
	 */
	private $name = '';

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $origName;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $realName;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	private $orealName;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=50, nullable=true)
	 */
	private $lastName;

	/**
	 * @var Country
	 * @ORM\ManyToOne(targetEntity="Country")
	 * @ORM\JoinColumn(name="country", referencedColumnName="code", nullable=false)
	 */
	private $country;

	/** @ORM\Column(type="boolean") */
	private $isAuthor = true;

	/** @ORM\Column(type="boolean") */
	private $isTranslator = false;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=160, nullable=true)
	 */
	private $info;

	/**
	 * @var Person
	 * @ORM\ManyToOne(targetEntity="Person")
	 */
	private $person;

	/**
	 * @var string
	 * @ORM\Column(type="string", length=1, nullable=true)
	 */
	private $type;

//	/**
//	 * @var TextAuthor[]
//	 * @ORM\OneToMany(targetEntity="TextAuthor", mappedBy="person")
//	 */
//	private $textAuthors;
//
//	/**
//	 * @var TextTranslator[]
//	 * @ORM\OneToMany(targetEntity="TextTranslator", mappedBy="person")
//	 */
//	private $textTranslators;

	/**
	 * @var Book[]
	 * @ORM\ManyToMany(targetEntity="Book", mappedBy="authors")
	 * @ORM\JoinTable(name="book_author")
	 */
	private $books;

	/**
	 * @var Series[]
	 * @ORM\ManyToMany(targetEntity="Series", mappedBy="authors")
	 * @ORM\JoinTable(name="series_author")
	 */
	private $series;

	public function getId() { return $this->id; }

	public function setSlug($slug) { $this->slug = Stringy::slugify($slug); }
	public function getSlug() { return $this->slug; }

	public function setName($name) {
		$this->name = $name;
		$this->lastName = self::getLastNameFromName($name);
		if (empty($this->slug)) {
			$this->setSlug($name);
		}
	}
	public function getName() { return $this->name; }

	public function getLastNameFromName($name) {
		preg_match('/([^,]+) ([^,]+)(, .+)?/', $name, $m);
		return isset($m[2]) ? $m[2] : $name;
	}

	public function setOrigName($origName) {
		$this->origName = $origName;
		if (empty($this->slug) && preg_match('/[a-z]/', $origName)) {
			$this->setSlug($origName);
		}
	}
	public function getOrigName() { return $this->origName; }

	public function setRealName($realName) { $this->realName = $realName; }
	public function getRealName() { return $this->realName; }

	public function setOrealName($orealName) { $this->orealName = $orealName; }
	public function getOrealName() { return $this->orealName; }

	public function getLastName() { return $this->lastName; }

	public function setCountry($country) { $this->country = $country; }
	public function getCountry() { return $this->country; }

	public function getIsAuthor() { return $this->isAuthor; }
	public function getIsTranslator() { return $this->isTranslator; }
	public function setIsAuthor($isAuthor) { $this->isAuthor = $isAuthor; }
	public function setIsTranslator($isTranslator) { $this->isTranslator = $isTranslator; }

	public function isAuthor($isAuthor = null) {
		if ($isAuthor !== null) {
			$this->isAuthor = $isAuthor;
		}
		return $this->isAuthor;
	}

	public function isTranslator($isTranslator = null) {
		if ($isTranslator !== null) {
			$this->isTranslator = $isTranslator;
		}
		return $this->isTranslator;
	}

	public function getRole() {
		$roles = [];
		if ($this->isAuthor) $roles[] = 'author';
		if ($this->isTranslator) $roles[] = 'translator';

		return implode(',', $roles);
	}

	public function setInfo($info) { $this->info = $info; }
	public function getInfo() { return $this->info; }

	public function setPerson($person) { $this->person = $person; }
	public function getPerson() { return $this->person; }

	public function setType($type) { $this->type = $type; }
	public function getType() { return $this->type; }

	public function getBooks() { return $this->books; }
	public function getSeries() { return $this->series; }

	public function __toString() {
		return $this->name;
	}

	/**
	 * Specify data which should be serialized to JSON
	 * @link http://php.net/manual/en/jsonserializable.jsonserialize.php
	 * @return array
	 */
	public function jsonSerialize() {
		return [
			'id' => $this->getId(),
			'slug' => $this->getSlug(),
			'name' => $this->getName(),
			'lastName' => $this->getLastName(),
			'origName' => $this->getOrigName(),
			'realName' => $this->getRealName(),
			'origRealName' => $this->getOrealName(),
			'isAuthor' => $this->isAuthor(),
			'isTranslator' => $this->isTranslator(),
			'info' => $this->getInfo(),
			'type' => $this->getType(),
		];
	}
}

src/Controller/AuthorController.php
<?php namespace App\Controller;

use App\Entity\Person;
use App\Pagination\Pager;
use App\Persistence\BookRepository;
use App\Persistence\PersonRepository;
use App\Persistence\TextRepository;
use App\Persistence\UserRepository;
use App\Service\SearchService;
use Symfony\Component\HttpFoundation\Request;

class AuthorController extends PersonController {

	public function __construct(UserRepository $userRepository, PersonRepository $personRepository) {
		parent::__construct($userRepository, $personRepository->asAuthor());
	}

	public function showBooksAction(BookRepository $bookRepository, $slug) {
		$person = $this->tryToFindPerson($slug);
		if ( ! $person instanceof Person) {
			return $person;
		}

		return [
			'person' => $person,
			'books'  => $bookRepository->findByAuthor($person),
		];
	}

	public function showTextsAction(TextRepository $textRepository, $slug, $_format) {
		$person = $this->tryToFindPerson($slug);
		if ( ! $person instanceof Person) {
			return $person;
		}

		$groupBySeries = $_format == 'html';
		return [
			'person' => $person,
			'texts'  => $textRepository->findByAuthor($person, $groupBySeries),
		];
	}

	public function searchAction(SearchService $searchService, Request $request, $_format) {
		$query = $request->query->get('q');
		if ($_format == 'json') {
			$persons = $this->findByQuery([
				'text'  => $query,
				'by'    => 'name,origName',
				'limit' => static::PAGE_COUNT_LIMIT,
			]);
			return $persons;
		}
		if ($_format == 'suggest') {
			$persons = $this->findByQuery([
				'text'  => $query,
				'by'    => 'name',
				'match' => 'prefix',
				'limit' => static::PAGE_COUNT_LIMIT,
			]);
			$items = $descs = $urls = [];
			foreach ($persons as $person) {
				$items[] = $person->getName();
				$descs[] = '';
				$urls[] = $this->generateAbsoluteUrl('author_show', ['slug' => $person->getSlug()]);
			}

			return [$query, $items, $descs, $urls];
		}
		return [];
	}

	protected function getShowTemplateParams(TextRepository $textRepository, BookRepository $bookRepository, Person $person, $format) {
		return $this->getShowTemplateParamsAuthor($textRepository, $bookRepository, $person, $format);
	}
}

templates/Author/index.html.twig
{% extends 'layout.html.twig' %}

{% set title = 'authors'|trans %}
{% block head %}
	{{ parent() }}
	<link rel="search" type="application/opensearchdescription+xml" href="{{ path('authors_search', {'_format': 'osd'}) }}" title="Търсене на автори в Моята библиотека" />
	<link rel="search" type="application/opensearchdescription+xml" href="{{ path('persons_search', {'_format': 'osd'}) }}" title="Търсене на личности в Моята библиотека" />
{% endblock %}
{% block content %}
	{% include 'Author/navigation.html.twig' with {'by': '', 'letter': ''} %}
	{% import 'helper.html.twig' as helper %}
	<h2>Държава</h2>
	<ul>
		{% for country in countries %}
			<li>
				<a href="{{ path('authors_by_country', {'country': country.code}) }}">{{ country.name }}</a>
				{{ helper.printNrOfItems(country.nrOfAuthors) }}
			</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/Author/index.opds.twig
{% extends 'layout.opds.twig' %}
{% import 'helper.opds.twig' as helper %}

{% set link_self = helper.path('authors') %}
{% set title = 'Автори' %}
{% block content %}
	{{ helper.navi_entry('По малко име', updated_at, 'authors_by_alpha_index', {'by': 'first-name'}, 'Списък на авторите по малко име') }}
	{{ helper.navi_entry('По фамилия', updated_at, 'authors_by_alpha_index', {'by': 'last-name'}, 'Списък на авторите по фамилия') }}
	{{ helper.navi_entry('По държава (по малко име)', updated_at, 'authors_by_country_index', {'by': 'first-name'}, 'Списък на авторите по държава, сортирани по малко име') }}
	{{ helper.navi_entry('По държава (по фамилия)', updated_at, 'authors_by_country_index', {'by': 'last-name'}, 'Списък на авторите по държава, сортирани по фамилия') }}
{% endblock %}

templates/Author/list.html.twig
{% import 'link.html.twig' as link %}
{% macro link(person, by) %}
	<a href="{{ path('person_show', {'slug': person.slug}) }}" itemprop="url" data-edit="{{ link.admin_person_edit(person) }}">{{ person.name|name_format(by)|raw }}</a>
{% endmacro %}

<ul class="superlist">
{% for author in persons %}
	<li><dl itemscope itemtype="http://schema.org/Person">
		{% if author.person is not empty %}
			<dt>
				{{ _self.link(author, by) }}
				&rarr;
				{{ _self.link(author.person, by) }}
			</dt>
		{% else %}
			<dt>{{ _self.link(author, by) }}</dt>
		{% endif %}
		<dd class="orig-name">{{ author.origName ? author.origName|name_format(by)|raw : '—' }}</dd>
	</dl></li>
{% else %}
	<li class="no-items">
		{% import 'helper.html.twig' as helper %}
		{{ helper.not_found('Няма намерени автори.') }}
	</li>
{% endfor %}
</ul>

templates/Author/list_by_alpha.html.twig
{% extends 'layout.html.twig' %}

{% set title = ('authors.by.'~by)|trans ~': '~ (letter == '-' ? 'Всички' : letter) %}
{% block content %}

	{% include 'Author/navigation.html.twig' %}
	{% include 'Author/list_with_country.html.twig' %}
	{% include 'pager.html.twig' %}

{% endblock %}

templates/Author/list_by_alpha_index.opds.twig
{% extends 'layout.opds.twig' %}
{% import 'helper.opds.twig' as helper %}

{% set link_self = helper.path('authors_by_alpha_index', {'by': by}) %}
{% set title = ('authors.by.'~by)|trans %}
{% block content %}
	{{ helper.letter_links('authors_by_alpha', {'by': by}) }}
{% endblock %}

templates/Author/list_by_country.html.twig
{% extends 'layout.html.twig' %}

{% set title = ('authors.by.country.'~by)|trans ~ ': ' ~ country.name %}
{% block content %}

	{% include 'Author/list.html.twig' %}
	{% include 'pager.html.twig' %}

{% endblock %}

templates/Author/list_with_country.html.twig
{% import 'link.html.twig' as link %}
{% if by is not defined %}
	{% set by = 'first-name' %}
{% endif %}
<ul class="superlist">
{% for author in persons %}
	<li><dl itemscope itemtype="http://schema.org/Person">
		{% if author.person is not empty %}
			<dt>
				<a href="{{ path('person_show', {'slug': author.slug}) }}" itemprop="url" data-edit="{{ link.admin_person_edit(author) }}">{{ author.name|name_format(by)|raw }}</a>
				&rarr;
				<a href="{{ path('person_show', {'slug': author.person.slug}) }}" itemprop="url" data-edit="{{ link.admin_person_edit(author.person) }}">{{ author.person.name|name_format(by)|raw }}</a>
			</dt>
			<dd class="orig-name">{{ author.origName ? author.origName|name_format(by)|raw : '—' }}</dd>
			<dd class="country">{{ link.authors_by_country(author.person.country) }}</dd>
		{% else %}
			<dt><a href="{{ path('person_show', {'slug': author.slug}) }}" itemprop="url" data-edit="{{ link.admin_person_edit(author) }}">{{ author.name|name_format(by)|raw }}</a></dt>
			<dd class="orig-name">{{ author.origName ? author.origName|name_format(by)|raw : '—' }}</dd>
			<dd class="country" itemprop="nationality" itemscope itemtype="http://schema.org/Country">{{ link.authors_by_country(author.country) }}</dd>
		{% endif %}
	</dl></li>
{% else %}
	<li class="no-items">
		{% import 'helper.html.twig' as helper %}
		{{ helper.not_found('Няма намерени автори.') }}
	</li>
{% endfor %}
</ul>

templates/Author/navigation.html.twig
{% import 'navi.html.twig' as navi %}
{% if by == 'first-name' or by == '' %}
	<h2>Име</h2>
	<div class="first-name text-center">
		{{ navi.person_first_letter_links('authors_by_alpha', (by == 'first-name' ? letter : '')) }}
	</div>
{% endif %}
{% if by == 'last-name' or by == '' %}
	<h2>Фамилия</h2>
	<div class="last-name text-center">
		{{ navi.person_last_letter_links('authors_by_alpha', (by == 'last-name' ? letter : '')) }}
	</div>
{% endif %}

templates/Author/search.osd.twig
{% extends 'layout.osd.twig' %}
{% set title = 'автори' %}

templates/Author/show.opds.twig
{% extends 'layout.opds.twig' %}
{% import 'helper.opds.twig' as helper %}

{% set link_self = helper.path('author_show', {'slug': person.slug}) %}
{% set title = person.name ~ ' (автор)' %}
{% block content %}
	{% if books is defined %}
		{% include 'Book/list.opds.twig' %}
	{% endif %}
	{% include 'Text/list.opds.twig' with {'texts': texts_as_author} %}
{% endblock %}

templates/Author/show_books.html.twig
{% extends 'layout.html.twig' %}

{% import 'link.html.twig' as link %}
{% set title %}
	<a class="selflink" itemprop="name" data-edit="{{ link.admin_person_edit(person) }}">{{ person.name }}</a>
{% endset %}
{% set subtitle = ('person.role.'~person.role)|trans %}
{% block content %}
	<div class="person-{{ person.slug }}">
	{% if books is defined %}
		<h2 id="books">Книги</h2>
		{% include 'Book/list.html.twig' %}
	{% endif %}
	</div>
{% endblock %}

templates/Author/show_books.opds.twig
{% extends 'layout.opds.twig' %}
{% import 'helper.opds.twig' as helper %}

{% set link_self = helper.path(current_route, {'slug': person.slug}) %}
{% set title = person.name ~ ' (автор)' %}
{% block content %}
	{% if books is defined %}
		{% include 'Book/list.opds.twig' %}
	{% endif %}
{% endblock %}

templates/Author/show_texts.html.twig
{% extends 'layout.html.twig' %}

{% import 'link.html.twig' as link %}
{% set title %}
	<a class="selflink" itemprop="name" data-edit="{{ link.admin_person_edit(person) }}">{{ person.name }}</a>
{% endset %}
{% set subtitle = ('person.role.'~person.role)|trans %}
{% block content %}
	<div class="person-{{ person.slug }}">
	{% if texts|length > 0 %}
		<h2 id="author">Произведения</h2>
	{% endif %}
	{% for series in texts %}
		{% include 'Author/texts_list.html.twig' with {'series': series.data, 'texts': series.texts} %}
	{% endfor %}
	</div>
{% endblock %}

templates/Author/texts_list.html.twig
{% import 'text.html.twig' as text_lister %}
	<h3>
		{% if series.slug is defined %}
			<a href="{{ path('series_show', {'slug': series.slug}) }}">{{ series.name }}</a>
			{% if series.origName is not empty %}
				({{ series.origName }})
			{% endif %}
		{% else %}
			{{ series.name }}
		{% endif %}
	</h3>
	{{ text_lister.text_list(texts) }}
	{% if texts|length > 1 %}
		{% set filename = person.slug ~'_'~ ( series.slug is defined ? series.slug : series.name ) %}
		{% include 'Text/multi_download_form.html.twig' with {'filename': filename~''} %}
	{% endif %}