src/Chitanka/LibBundle/Controller/CRUDController.php
<?php

namespace Chitanka\LibBundle\Controller;

use Symfony\Component\HttpKernel\Exception\HttpException;
use Sonata\AdminBundle\Controller\CRUDController as BaseController;
use Chitanka\LibBundle\Entity\User;


class CRUDController extends BaseController
{
	public function configure()
	{
		if ( ! $this->getUser()->inGroup('admin')) {
			throw new HttpException(401);
		}

		parent::configure();
	}


	public function getUser()
	{
		if ( ! isset($this->_user)) {
			$this->_user = User::initUser($this->getRepository('User'));
		}

		return $this->_user;
	}

	public function getRepository($entityName)
	{
		return $this->get('doctrine.orm.entity_manager')->getRepository('LibBundle:'.$entityName);
	}

}

src/Chitanka/LibBundle/Resources/views/Search/books.html.twig
{% extends 'LibBundle::layout.html.twig' %}

{% set title = 'Търсене' ~ (query ? ' на „'~query.text~'“' : '') ~ ' в книгите' %}
{% block content %}

	{% if books|length %}
		{% include 'LibBundle:Book:list.html.twig' %}
	{% endif %}

	{% if not found %}
		<p class="no-items">Нямате късмет. Не открихме никакви книги.</p>
	{% endif %}

{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/books.xml.twig
{% extends 'LibBundle::layout.xml.twig' %}
{% block body %}
<results query="{{ query.text }}">
	{% include 'LibBundle:Book:list.xml.twig' %}
</results>
{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/persons.html.twig
{% extends 'LibBundle::layout.html.twig' %}

{% set title = 'Търсене' ~ (query ? ' на „'~query.text~'“' : '') ~ ' в личности' %}
{% block content %}

	{% if persons|length %}
		{% include 'LibBundle:Author:list_with_country.html.twig' with {'authors': persons} %}
	{% endif %}

	{% if not found %}
		<p class="no-items">Нямате късмет. Не открихме никакви личности.</p>
	{% endif %}

{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/persons.xml.twig
{% extends 'LibBundle::layout.xml.twig' %}
{% block body %}
<results query="{{ query.text }}">
	{% include 'LibBundle:Person:list.xml.twig' %}
</results>
{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/sequences.html.twig
{% extends 'LibBundle::layout.html.twig' %}

{% set title = 'Търсене' ~ (query ? ' на „'~query.text~'“' : '') ~ ' в издателските поредици' %}
{% block content %}

	{% if sequences|length %}
		{% include 'LibBundle:Sequence:list.html.twig' %}
	{% endif %}

	{% if not found %}
		<p class="no-items">Нямате късмет. Не открихме никакви издателски поредици.</p>
	{% endif %}

{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/sequences.xml.twig
{% extends 'LibBundle::layout.xml.twig' %}
{% block body %}
<results query="{{ query.text }}">
	{% include 'LibBundle:Sequence:list.xml.twig' %}
</results>
{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/series.html.twig
{% extends 'LibBundle::layout.html.twig' %}

{% set title = 'Търсене' ~ (query ? ' на „'~query.text~'“' : '') ~ ' в авторските поредици' %}
{% block content %}

	{% if series|length %}
		{% include 'LibBundle:Series:list.html.twig' %}
	{% endif %}

	{% if not found %}
		<p class="no-items">Нямате късмет. Не открихме никакви авторски поредици.</p>
	{% endif %}

{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/series.xml.twig
{% extends 'LibBundle::layout.xml.twig' %}
{% block body %}
<results query="{{ query.text }}">
	{% include 'LibBundle:Series:list.xml.twig' %}
</results>
{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/texts.html.twig
{% extends 'LibBundle::layout.html.twig' %}

{% set title = 'Търсене' ~ (query ? ' на „'~query.text~'“' : '') ~ ' в произведенията' %}
{% block content %}

	{% if texts|length %}
		{% include 'LibBundle:Text:list.html.twig' %}
	{% endif %}

	{% if not found %}
		<p class="no-items">Нямате късмет. Не открихме никакви произведения.</p>
	{% endif %}

{% endblock %}

src/Chitanka/LibBundle/Resources/views/Search/texts.xml.twig
{% extends 'LibBundle::layout.xml.twig' %}
{% block body %}
<results query="{{ query.text }}">
	{% include 'LibBundle:Text:list.xml.twig' %}
</results>
{% endblock %}

src/Chitanka/LibBundle/Resources/views/Text/label_list.atom.twig
{% for label in labels %}
	<entry>
		<title>{{ label.name }}</title>
		<id>{{ helper.urn('texts_by_label', [label.slug]) }}</id>
		{{ helper.link(helper.url('texts_by_label', {'slug': label.slug})) }}
		<content type="text">Произведения с етикет „{{ label.name }}“. Общо: {{ label.nr_of_texts }}</content>
	</entry>
{% endfor %}

src/Chitanka/LibBundle/Resources/views/Text/texts_list.html.twig
{% import 'LibBundle::text.html.twig' as texttools %}
{{ texttools.text_list_with_author(texts) }}

src/Chitanka/LibBundle/Resources/views/Text/type_list.atom.twig
{% for type in types %}
	<entry>
		<title>{{ ('text.type.singular.'~type) | trans }}</title>
		<id>{{ helper.urn('texts_by_type', [type]) }}</id>
		{{ helper.link(helper.url('texts_by_type', {'type': type})) }}
		<content type="text">Произведения от вид „{{ ('text.type.singular.'~type) | trans }}“</content>
	</entry>
{% endfor %}

src/Chitanka/LibBundle/Resources/views/Workroom/entries_list.html.twig
<table class="content sortable">
<thead>
	<tr>
		<th>Дата</th>
		<th></th>
		<th></th>
		<th></th>
		<th style="width: 25%">Заглавие</th>
		<th>Автор</th>
		<th>Етап на работата</th>
		<th>Потребител</th>
	</tr>
</thead>
<tbody>
{% for entry in entries %}
	<tr class="{{ cycle(['even', 'odd'], loop.index) }} {{ entry.is_frozen ? 'frozen' : '' }}" id="e{{ entry.id }}">
		{% include 'LibBundle:Workroom:entry.html.twig' %}
	</tr>
{% endfor %}
</tbody>
</table>

src/Chitanka/LibBundle/Resources/views/Workroom/entry.html.twig
<td class="date" title="{{ entry.date|humandate }}">{{ entry.date.format('d.m.Y') }}</td>
<td>
	<span class="{{ entry.type == 1 ? 'multiuser' : 'singleuser' }}"><span>{{ ('workroom.type.'~entry.type) | trans }}</span></span>
</td>
<td>
	{% if entry.comment %}
		<span class="act-info tooltip" title="{{ entry.comment }}"><span>Инфо</span></span>
	{% endif %}
</td>
<td>
	{% if entry.tmpfiles %}
		<a href="{{ entry.tmpfiles }}" class="save"><span>Файл</span></a>
	{% endif %}
</td>
<td><a href="{{ path('workroom_entry_edit', {'id': entry.id}) }}"><i>{{ entry.title }}</i></a></td>
<td>{{ entry.author }}</td>
<td>
	{% if entry.progress %}
		{{ progressbar(entry.progress)|raw }}
	{% else %}
		<span class="progress progress-{{ entry.status }}">{{ ('workroom.status.'~entry.status) | trans }}</span>
	{% endif %}
	{% if entry.is_frozen %}
		<span title="Подготовката е замразена">(замразена)</span>
	{% endif %}
</td>
<td>
	{% import 'LibBundle::link.html.twig' as link %}
	<ul class="simplelist">
		<li>{{ link.user_with_email(entry.user) }}</li>
		{% for contrib in entry.contribs %}
			<li>{{ link.user_with_email(contrib.user) }}<span class="act-info tooltip" title="{{ contrib.comment }}"><span>Инфо</span></span></li>
		{% endfor %}
	</ul>
</td>

src/Chitanka/LibBundle/Resources/views/Workroom/latest_entries.html.twig
<table class="content sortable">
<thead>
	<tr>
		<th>Дата</th>
		<th></th>
		<th></th>
		<th></th>
		<th style="width: 25%">Заглавие</th>
		<th>Автор</th>
		<th>Етап на работата</th>
		<th>Потребител</th>
	</tr>
</thead>
<tbody>
{% for entry in entries %}
	<tr class="{{ cycle(['even', 'odd'], loop.index) }} {{ entry.is_frozen ? 'frozen' : '' }}" id="e{{ entry.id }}">
		{% include 'LibBundle:Workroom:entry.html.twig' %}
	</tr>
{% endfor %}
</tbody>
</table>